os: linux
dist: xenial
language: java
jdk: openjdk11

env:
  global:
    #GITHUB_TOKEN
    - secure: "qxNcLCilGoOy2SYn/Hl2tkSxOHVJX2t32afvlK7z2SLQ7S7mzcPmV6PfFc6VlI5c1HrrlPN46qUEtZMuqZaP+R4rZXETXu/r4j+GP9KxSNowSLhGiBEWuzaZ5Fp6ZgCVxRTHl9AnEHgt5hmYzjI35Olty7c49NqXZhFDPpiARkFecaK0roHDYA1KdC+I1BlRXCtBDG1dS0oqM9LUQmkiAj39RuT1OnGCd04oEczqb0IvDTWtkWvof2Yq2P9oEhjKGgasSDlxgMOkBh4Mq4LVvt5AEZq1JqQ/fgr7Zsswc6I2hjYdkTU64G52y5sCRk4w/4CtbZwYRiDGadpHCvye2z/sZEzSAeZPd3uYNDd1nq6HqVFBPIp9yButYafPlqHXEvZ3xKP1xzp9JnPEIRLGG+h/+bqa+5udAYpUtYovnqcObsC3OVH4cbjkrdl1s0D06qH7srcEJnj/T8cwR7wLMoLyVnb3dn6XcH9D9JlQuP8x/g64RbLxg9kbnTUVB3iTwlCXZHkVSELxfNF2S8X1htS2z+ZmflG6JhPhbfs/EJd0ZrsC2TOnRqmsR529x2jR+UMDgIX1mXhqF1oCkh9qaidHsjWB8aS3FwCj/xvWQhHbqFnRoXMoaxuLp5X90rhVkcH2V6FrtTLOMyC4bzdd4qx9Y7rPoQLT02lpAXt/UBY="

after_success:

    #UPDATE JAVADOC REPORT

    - chmod u+x $HOME/build/xxcw/marketplace-webapp-client/scripts/javadocs.sh
    - bash $HOME/build/xxcw/marketplace-webapp-client/scripts/javadocs.sh