os: linux
dist: xenial
language: java
jdk: openjdk11

env:
  global:
    #GITHUB_TOKEN
    - secure: jNpm5OdgoySYlTv5AEEq3D/ffAmpUhSK+5X9qdNJ1u4sl8GyRs2/ySazdPerowLTX+xZ93TxgjKb7XtKJm4I435MxasJ8VA8Bviu5G/vURygRGb/h+QeUAgMxTvHIszZN8dYEoazs3EmgJJ+n0g74J/vyjQceccpv5hZYNwfqyknJeEiJUtjivH2wZlkem5hXItz3PjN/VMdG/DL6pHnnPmylBdFA/c7UFv2xXVqv88C3I6wtYNlOjLqKPLI2mmMtDFZfQz19/xHjpE/clnfTEHmCU53pQObtkUTZa8Gk9SCSxoFUU4K190C1PKyFvfcN6lsOo+O3az9JIowreRHx7QGfLhUn1jMojKxFii7/4JM05HqPubMZKUh28q362YZQzxCPRvtf0731192mM5w/tCw6bPrOQ9qz5SFu+X5Dgm5ZK8b1ceuU8HCZr9dujUsSaAE+Vd3p58pDiEOEiXYN0ECTu/0a8DC7N2T8OXLpdwlhY9S2FUZGRyd1dc6NpygRu5LObTcY03CgOtuMiQtYbNHWZCdD0hppJGNajwV4BwhOwwEm7rG1YSWY45n1/4HzA9McLJFHAzpvsM0yEcpVykWh3YoOhftH87uShccDx/EQqQ6wpPi9slxp5P8M8aJ3kUFE+u557DE2ud6f5eN7dYhwVlQ+29kK8q0N2S19c0=

after_success:

    #UPDATE JAVADOC REPORT

    - chmod u+x $HOME/build/xxcw/marketplace-webapp-client/scripts/javadocs.sh
    - bash $HOME/build/xxcw/marketplace-webapp-client/scripts/javadocs.sh