os: linux
dist: xenial
language: java
jdk: openjdk11

env:
  global:
    #GITHUB_TOKEN
    - secure: "qxNcLCilGoOy2SYn/Hl2tkSxOHVJX2t32afvlK7z2SLQ7S7mzcPmV6PfFc6VlI5c1HrrlPN46qUEtZMuqZaP+R4rZXETXu/r4j+GP9KxSNowSLhGiBEWuzaZ5Fp6ZgCVxRTHl9AnEHgt5hmYzjI35Olty7c49NqXZhFDPpiARkFecaK0roHDYA1KdC+I1BlRXCtBDG1dS0oqM9LUQmkiAj39RuT1OnGCd04oEczqb0IvDTWtkWvof2Yq2P9oEhjKGgasSDlxgMOkBh4Mq4LVvt5AEZq1JqQ/fgr7Zsswc6I2hjYdkTU64G52y5sCRk4w/4CtbZwYRiDGadpHCvye2z/sZEzSAeZPd3uYNDd1nq6HqVFBPIp9yButYafPlqHXEvZ3xKP1xzp9JnPEIRLGG+h/+bqa+5udAYpUtYovnqcObsC3OVH4cbjkrdl1s0D06qH7srcEJnj/T8cwR7wLMoLyVnb3dn6XcH9D9JlQuP8x/g64RbLxg9kbnTUVB3iTwlCXZHkVSELxfNF2S8X1htS2z+ZmflG6JhPhbfs/EJd0ZrsC2TOnRqmsR529x2jR+UMDgIX1mXhqF1oCkh9qaidHsjWB8aS3FwCj/xvWQhHbqFnRoXMoaxuLp5X90rhVkcH2V6FrtTLOMyC4bzdd4qx9Y7rPoQLT02lpAXt/UBY="
    #TELEGRAM_BOT_TOKEN
    - secure: "NVS6/puNFpaq31WjW262hSR8nWNatzcH+uXDgijGblS16K3UARADh7zjvfOW6MTs1aaDqz8bsNmh4maEoExQToZQmpOfrx3IdNsfZa4gXpJEdAbhUZ/gGnILPAAahMY6XHtKqVPLdbC21JJNaZYnmCGFyhmMarjQXGTclhHB6dfG5OX0A2ezBmMUCtLjmve+Gzdtt0J5n/90OHj7CLwYaDZ7wFBrmt+qU/HR4/U1iV2Mk3DqyXm+eSFCS5X80vIa9XYpTSMMYnB0KLWiE562maCdEnHwM4rxsF/aGAvyi1y809U48+TN6UQ9lO/2YhZY7gzkl9GRpw00V0Eoc8e5sBRkBorgI8D1QymnvCS/3s8A9EowbzuNMM3fbmUXWq+NTgAQRY5t8MZgiVYbVLMbtq+3h9ExEQwmO92Z975RlyesHqoHTr7fPwB+j/cA/OFcnKhSZ/fxXWkQslWe+ZC04IDg3Ir/CH2dPSaeA35NPFt7ATVhJepa9Ao9fSZWxYaTqyf7XUoHG4oBP7K58ojBGH0cYV1TD1FZKw5Eo4XrV7HkzqmjjbyvPk8vlJ7zcUCi0GO1EE0D2EDuTyICM3d0eMfy/Dx6ALGP+9OfNGMAg+667grqZjLd5c/X8asWiA/qFncThK+utmXqAMIX/OLpxSnSouRnN7qoEpIIEAI23lE="
#HEROKU

deploy:
  provider: heroku
  app: marketplace-webapp-client
  api_key:
    secure: "AZXnjslOeUOD1dPOTkkjwPUdwqberr9WqvfY0STFtsBPlXhrEZBC0JoBbR6xJLaOCC4ZS910heb2gQctTXj4Ot6UQCf9Djepfb6X8Tqvv+Pv3pw9UoV4QNoBIXeRkZCfUbSG8rE2Ry4XUWvSr37gZ6V2Fz8sOz+CnCKTBhm0+78qqLqSMJV7GUW+ds6M0pQb1KrvuWML724cwMVy6zfbiLapqAu8LkvUGcoh6THZcMdvJQUKNHz+uYewVxqvooCdPS8dINsmd2uJqzgMub8SsAcHQMmPYizZ89WrS1Tq8Bxg+4ljr3J6SXLK9Bo3UFJeqQj4KrRAR5iEzU5oAln53EWL3ZnD6rrclGU5U9Yg+cN8tSdv9m8rxStQf6QzKwDlopY+ZT5pLi5Ed/afeCUu/0v8Iy+kN4s6SzeNz5LC/5jzr01U+VHFkGenGDEz3KcO0AP1ftLSOcfRDl7179FrUgOUd5JURMvr3zrrki2CuhRJcIV8eL9XRsYcjpols74MtlvsBAI3fExQgImVK4xUmA301B0BKdAlgTItHHsEHndJnTBG0r5u2Ve3Cksnf2n+JXmJT+gnAk5AYACKNxllc4imsUizuoewLzpGiKMJCIUgEDyUuDtDH+wzCLD4BfsU9bjELU71n4fshllMiCFhp5WBDNAHlhRlhnrHCU68ADk="

#SONARCLOUD

addons:
  sonarcloud:
    organization: "xxcw"
    token:
      secure: "CpTHhEjsoAdmDhmWziKt5KABumQkIZ6fFn9lxZ5llJrSi1PgQv2XcFpAdWRZHuSZt0jXRufUow1Zt0Q4ncJgIqXBG/d2LwgtbJyVv2ONB+F6qypFq3KfaBtog46d/igzUqXlQve/4eNDbW1X6f8SeVx6GAyd9TWg3I1WbAI/8dKOGOD+HzBr5uWvl2/DR3PXhJlWuPencCcDhEA37iOgYlvKpU5GaexyGEn9wH2HWOhihi+X2ElWJSFq7cHAShltihDNKlOLkmaIrcBPaqg7gVLKdy+bOBvm04ewkp4T6Uz7XBOcn0ONZMogmmbkPn3SIxX0gHJ+AmOoFaEsrZhZfdJCWNNE1jFRrasbEB66NitEenYoE+CBnD18DLnBYOaU21E1eJnI6N12ZqBojKWt1Ac2PfwvgnO4Vdvx7F0aPqLq3laIOfQAvK0K4yqqfw8RvsZIdLbr22Ie8iSaMK3gOmlXoaqWcGgrHy1w2GV8IEzbP7XIM57jcLPJZk8T28SwJF4CanP3YYuFXkUZ1h9e6tdktZeYMxoHBvorM++idYeZr3yD2K4hf+DzAYq7yAogXglJUJXQ0ZqStGf5AglURsp8XkYGbw8jB02/HQ4JixEIaKdjyHDjIz9n8PIsD6YnNRkNj7FfqG+l3hcHYkQLYcOXUwbcNL9xmnolDKa9x3g="
script:
    - mvn clean verify sonar:sonar -Pcoverage -X

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

after_success:

    #TELEGRAM NOTIFICATION

    - curl -d "chat_id=@travis_client_reports&text=build $TRAVIS_BUILD_NUMBER passed. %0A$TRAVIS_COMMIT_MESSAGE" -X POST https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage

    #UPDATE JAVADOC REPORT

    - chmod u+x $HOME/build/xxcw/marketplace-webapp-client/scripts/javadocs.sh
    - bash $HOME/build/xxcw/marketplace-webapp-client/scripts/javadocs.sh